import { byId } from "../utils/dom.js";

export type DomRefs = {
  runBtn: HTMLButtonElement;
  runModeBtn: HTMLButtonElement;
  runGroup: HTMLDivElement;
  runMenu: HTMLDivElement;
  runAllBtn: HTMLButtonElement;
  runSelBtn: HTMLButtonElement;
  runCellBtn: HTMLButtonElement;
  runLabel: HTMLSpanElement;
  openBtn: HTMLButtonElement;
  saveBtn: HTMLButtonElement;
  shareBtn: HTMLButtonElement;
  fileInput: HTMLInputElement;
  moreBtn: HTMLButtonElement;
  moreMenu: HTMLDivElement;
  shareMenuBtn: HTMLButtonElement;
  resetBtn: HTMLButtonElement;
  settingsBtn: HTMLButtonElement;
  aboutBtn: HTMLButtonElement;
  wrapBtn: HTMLButtonElement;
  editorPane: HTMLDivElement;
  resizer: HTMLDivElement;
  consoleEl: HTMLDivElement;
  clearConsoleBtn: HTMLButtonElement;
  undoClearBtn: HTMLButtonElement;
  aboutOverlay: HTMLDivElement;
  closeAboutBtn: HTMLButtonElement;
  aboutVersion: HTMLSpanElement;
  aboutBuildTime: HTMLSpanElement;
  aboutCommitHash: HTMLSpanElement;
  settingsOverlay: HTMLDivElement;
  closeSettingsBtn: HTMLButtonElement;
  printOverlay: HTMLDivElement;
  printBtn: HTMLButtonElement;
  printCancelBtn: HTMLButtonElement;
  printConfirmBtn: HTMLButtonElement;
  printIncludeCode: HTMLInputElement;
  printIncludeOutput: HTMLInputElement;
  printLineNumbers: HTMLInputElement;
  printWrapLines: HTMLInputElement;
  printBranding: HTMLInputElement;
  printTimestamp: HTMLInputElement;
  printContentNote: HTMLDivElement;
  exportRoot: HTMLDivElement;
  shareWarnOverlay: HTMLDivElement;
  shareWarnText: HTMLDivElement;
  shareWarnCancelBtn: HTMLButtonElement;
  shareWarnDownloadBtn: HTMLButtonElement;
  shareWarnConfirmBtn: HTMLButtonElement;
  asyncWarnOverlay: HTMLDivElement;
  asyncWarnText: HTMLDivElement;
  asyncWarnCancelBtn: HTMLButtonElement;
  asyncWarnConfirmBtn: HTMLButtonElement;
  shareToast: HTMLDivElement;
  shareToastTitle: HTMLDivElement;
  shareToastDesc: HTMLDivElement;
  shareToastIcon: HTMLSpanElement;
  sysToast: HTMLDivElement;
  sysToastTitle: HTMLDivElement;
  sysToastDesc: HTMLDivElement;
  sysToastIcon: HTMLSpanElement;
  fileMeta: HTMLSpanElement;
  sbRun: HTMLSpanElement;
  sbDirty: HTMLSpanElement;
  sbPy: HTMLSpanElement;
  sbFile: HTMLSpanElement;
  sbPos: HTMLSpanElement;
  sbSel: HTMLSpanElement;
  sbClock: HTMLSpanElement;
  hintRun: HTMLSpanElement;
  hintOpen: HTMLSpanElement;
  hintSave: HTMLSpanElement;
  hintSettings: HTMLSpanElement;
  hintPrint: HTMLSpanElement;
  isolationBanner: HTMLDivElement;
  isolationBannerClose: HTMLButtonElement;
  editorSizeRange: HTMLInputElement;
  consoleSizeRange: HTMLInputElement;
  editorSizeLabel: HTMLSpanElement;
  consoleSizeLabel: HTMLSpanElement;
  wrapToggle: HTMLInputElement;
  execTimeToggle: HTMLInputElement;
  shortcutBody: HTMLTableSectionElement;
  dynamicStyles: HTMLStyleElement;
};

export function getDomRefs(): DomRefs {
  return {
    runBtn: byId<HTMLButtonElement>("runBtn"),
    runModeBtn: byId<HTMLButtonElement>("runModeBtn"),
    runGroup: byId<HTMLDivElement>("runGroup"),
    runMenu: byId<HTMLDivElement>("runMenu"),
    runAllBtn: byId<HTMLButtonElement>("runAllBtn"),
    runSelBtn: byId<HTMLButtonElement>("runSelBtn"),
    runCellBtn: byId<HTMLButtonElement>("runCellBtn"),
    runLabel: byId<HTMLSpanElement>("runLabel"),
    openBtn: byId<HTMLButtonElement>("openBtn"),
    saveBtn: byId<HTMLButtonElement>("saveBtn"),
    shareBtn: byId<HTMLButtonElement>("shareBtn"),
    fileInput: byId<HTMLInputElement>("fileInput"),
    moreBtn: byId<HTMLButtonElement>("moreBtn"),
    moreMenu: byId<HTMLDivElement>("moreMenu"),
    shareMenuBtn: byId<HTMLButtonElement>("shareMenuBtn"),
    resetBtn: byId<HTMLButtonElement>("resetBtn"),
    settingsBtn: byId<HTMLButtonElement>("settingsBtn"),
    aboutBtn: byId<HTMLButtonElement>("aboutBtn"),
    wrapBtn: byId<HTMLButtonElement>("wrapBtn"),
    editorPane: byId<HTMLDivElement>("editorPane"),
    resizer: byId<HTMLDivElement>("dragbar"),
    consoleEl: byId<HTMLDivElement>("console"),
    clearConsoleBtn: byId<HTMLButtonElement>("clearConsoleBtn"),
    undoClearBtn: byId<HTMLButtonElement>("undoClearBtn"),
    aboutOverlay: byId<HTMLDivElement>("aboutOverlay"),
    closeAboutBtn: byId<HTMLButtonElement>("closeAboutBtn"),
    aboutVersion: byId<HTMLSpanElement>("aboutVersion"),
    aboutBuildTime: byId<HTMLSpanElement>("aboutBuildTime"),
    aboutCommitHash: byId<HTMLSpanElement>("aboutCommitHash"),
    settingsOverlay: byId<HTMLDivElement>("settingsOverlay"),
    closeSettingsBtn: byId<HTMLButtonElement>("closeSettingsBtn"),
    printOverlay: byId<HTMLDivElement>("printOverlay"),
    printBtn: byId<HTMLButtonElement>("printBtn"),
    printCancelBtn: byId<HTMLButtonElement>("printCancelBtn"),
    printConfirmBtn: byId<HTMLButtonElement>("printConfirmBtn"),
    printIncludeCode: byId<HTMLInputElement>("printIncludeCode"),
    printIncludeOutput: byId<HTMLInputElement>("printIncludeOutput"),
    printLineNumbers: byId<HTMLInputElement>("printLineNumbers"),
    printWrapLines: byId<HTMLInputElement>("printWrapLines"),
    printBranding: byId<HTMLInputElement>("printBranding"),
    printTimestamp: byId<HTMLInputElement>("printTimestamp"),
    printContentNote: byId<HTMLDivElement>("printContentNote"),
    exportRoot: byId<HTMLDivElement>("exportRoot"),
    shareWarnOverlay: byId<HTMLDivElement>("shareWarnOverlay"),
    shareWarnText: byId<HTMLDivElement>("shareWarnText"),
    shareWarnCancelBtn: byId<HTMLButtonElement>("shareWarnCancelBtn"),
    shareWarnDownloadBtn: byId<HTMLButtonElement>("shareWarnDownloadBtn"),
    shareWarnConfirmBtn: byId<HTMLButtonElement>("shareWarnConfirmBtn"),
    asyncWarnOverlay: byId<HTMLDivElement>("asyncWarnOverlay"),
    asyncWarnText: byId<HTMLDivElement>("asyncWarnText"),
    asyncWarnCancelBtn: byId<HTMLButtonElement>("asyncWarnCancelBtn"),
    asyncWarnConfirmBtn: byId<HTMLButtonElement>("asyncWarnConfirmBtn"),
    shareToast: byId<HTMLDivElement>("shareToast"),
    shareToastTitle: byId<HTMLDivElement>("shareToastTitle"),
    shareToastDesc: byId<HTMLDivElement>("shareToastDesc"),
    shareToastIcon: byId<HTMLSpanElement>("shareToastIcon"),
    sysToast: byId<HTMLDivElement>("sysToast"),
    sysToastTitle: byId<HTMLDivElement>("sysToastTitle"),
    sysToastDesc: byId<HTMLDivElement>("sysToastDesc"),
    sysToastIcon: byId<HTMLSpanElement>("sysToastIcon"),
    fileMeta: byId<HTMLSpanElement>("fileMeta"),
    sbRun: byId<HTMLSpanElement>("sbRun"),
    sbDirty: byId<HTMLSpanElement>("sbDirty"),
    sbPy: byId<HTMLSpanElement>("sbPy"),
    sbFile: byId<HTMLSpanElement>("sbFile"),
    sbPos: byId<HTMLSpanElement>("sbPos"),
    sbSel: byId<HTMLSpanElement>("sbSel"),
    sbClock: byId<HTMLSpanElement>("sbClock"),
    hintRun: byId<HTMLSpanElement>("hintRun"),
    hintOpen: byId<HTMLSpanElement>("hintOpen"),
    hintSave: byId<HTMLSpanElement>("hintSave"),
    hintSettings: byId<HTMLSpanElement>("hintSettings"),
    hintPrint: byId<HTMLSpanElement>("hintPrint"),
    isolationBanner: byId<HTMLDivElement>("isolationBanner"),
    isolationBannerClose: byId<HTMLButtonElement>("isolationBannerClose"),
    editorSizeRange: byId<HTMLInputElement>("editorSizeRange"),
    consoleSizeRange: byId<HTMLInputElement>("consoleSizeRange"),
    editorSizeLabel: byId<HTMLSpanElement>("editorSizeLabel"),
    consoleSizeLabel: byId<HTMLSpanElement>("consoleSizeLabel"),
    wrapToggle: byId<HTMLInputElement>("wrapToggle"),
    execTimeToggle: byId<HTMLInputElement>("execTimeToggle"),
    shortcutBody: byId<HTMLTableSectionElement>("shortcutBody"),
    dynamicStyles: byId<HTMLStyleElement>("dynamicStyles")
  };
}
