// Generated by scripts/build-version.mjs. Do not edit.
export const APP_VERSION = "3.2";
export const BUILD_TIME = "2026-02-01T09:45:03.900Z";
export const COMMIT_HASH = "aeffe0bccd5e234e54e7ce26a11ee29741f45779";
